# Configurations
markdown: kramdown
markdown_ext:  markdown,mkdown,mkdn,mkd,md
highlighter: rouge

# Needed for backward compatibility
gems: [jekyll-paginate]

# Permalinks
permalink:        /blog/:year/:month/:day/:title

# Setup
title:            '刀剑尚未备好，转身已是江湖'
tagline:          'A Metro theme for Jekyll'
description:      'xiaoshuaigege blog'
url:              'https://xiaoshuaigege.github.io'
baseurl:          ''

# Navigation
navigation:
- text: About
  url: /about/
- text: Resume
  url: /resume/
- text: Blog
  url: /blog/
- text: Tags
  url: /tags/
- text: Archive
  url : /archive/
- text: Search
  url: /search/


# Author Details
author:         'xiaoshuaigege'
# 支持中文编码
encoding: 'utf-8'

#Social Media links (Use complete URL except for email)
dribbble:
email:
facebook:       ''
flickr:
github:         'https://github.com/xiaoshuaigege'
gplus:          ''
instagram:
pinterest:
linkedin:       ''
rss:
stackoverflow:  ''
twitter:        ''


# Google Analytics
# gahandler: 'UA-52149651-1'

#if footersvg is 'true' the social media links will be shown top on the copy right in the footer
footersvg: 'true'

# Disqus
disqushandler: 'testingblogo'

# txtpen
txtpenhandler: 'testingblogo'

# Blog Configurations
paginate: 10 # Posts per page on the blog index
paginate_path: '/blog/page:num'
destination: ./_site

# Custom vars
version:          0.9x beta 2
